url: "https://www.ontestautomation.com"
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"
title: "On Test Automation"
subtitle: "Improving your testing efforts through smart application of tools"
name: "Bas Dijkstra"
description: "Test automation training and consultancy"
logo: logo_large.png