url: "https://www.ontestautomation.com"
title: "On Test Automation"
title_separator: "|"
subtitle: "Helping others become better test automation engineers"
name: "Bas Dijkstra"
description: "Test automation training and consultancy"
logo: /images/logo_large.png
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-analytics
  - jekyll-feed
remote_theme: "mmistakes/minimal-mistakes@4.19.3"
minimal_mistakes_skin: "air"
markdown: kramdown
paginate: 5
paginate_path: "/blog/:num"
kramdown:
  syntax_highlighter: rouge
author_profile: true
author:
  name     : "Bas Dijkstra"
  avatar   : "/images/bas.png"
  bio      : "Helping others become better test automation engineers"
  location : "Amersfoort, the Netherlands"
  links:
    - label: LinkedIn
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/basdijkstra/"
    - label: GitHub
      icon: "fab fa-fw fa-github"
      url: "http://github.com/basdijkstra"
footer:
  links:
    - label: LinkedIn
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/basdijkstra/"
    - label: GitHub
      icon: "fab fa-fw fa-github"
      url: "http://github.com/basdijkstra"
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
jekyll_analytics:
  GoogleAnalytics:
    id: UA-176276927-1
analytics:
  provider: "google-universal"
  google:
    tracking_id: "UA-176276927-1"
commentbox:
  id: 5659931575320576-proj