url: "https://www.ontestautomation.com"
title: "On Test Automation"
title_separator: "|"
subtitle: "Improving your testing efforts through smart application of tools"
name: "Bas Dijkstra"
description: "Test automation training and consultancy"
logo: /images/logo_large.png
plugins:
  - jekyll-include-cache
remote_theme: "mmistakes/minimal-mistakes@4.19.3"
minimal_mistakes_skin: "air"
markdown: kramdown
paginate: 5
paginate_path: "page:num"
kramdown:
  syntax_highlighter: rouge
footer:
  links:
    - label: LinkedIn
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/basdijkstra/"
    - label: GitHub
      icon: "fab fa-fw fa-github"
      url: "http://github.com/basdijkstra"
